### Test index page

GET http://localhost:8080/

### Test fixtures/blake3.txt
GET http://localhost:8080/fixtures/blake3.txt

### Test tower-http
GET http://localhost:8080/Cargo.toml

### 
GET http://localhost:8080/tower/fixtures/blake3.txt

### 文件目录调用1
GET http://localhost:8080/fixtures

### 文件目录调用2
GET http://localhost:8080/src